# The version of circle ci platform to use
version: 2.1

jobs:
  test_node_14-17-5:
    docker:
      - image: circleci/node:14.17.5
      - image: mongo:4.4.8-focal
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install project dependencies
          command: npm install --verbose

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: npm run ci

  test_node_16-7-0:
    docker:
      - image: circleci/node:16.7.0
      - image: mongo:4.4.8-focal
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install project dependencies
          command: npm install --verbose

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: npm run ci
workflows:
  run_tests:
    jobs:
      - test_node_14-17-5
      - test_node_16-7-0
