# The version of circle ci platform to use
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
      - image: mongo:4.1.6-xenial
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install project dependencies
          command: npm install --verbose

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: npm run ci
workflows:
  run_build:
    jobs:
      - build
