# The version of circle ci platform to use
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  codecov: codecov/codecov@3.0.0
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
      - image: mongo:4.4.8-focal
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install project dependencies
          command: npm install --verbose

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: npm run ci

      - codecov/upload:
          file: ./coverage/clover.xml

      - discord/status:
          failure_message: ":o: Triggered by: **${CIRCLE_USERNAME}** \\n\\n The **${CIRCLE_JOB}** has failed!"
          success_message: ":white_check_mark: Triggered by: **${CIRCLE_USERNAME}** \\n\\n The **${CIRCLE_JOB}** has succeeded!"

workflows:
  build_deploy:
    jobs:
      - build

      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main
          post-steps:
            - discord/status:
                failure_message: ":o: Triggered by: **${CIRCLE_USERNAME}** \\n\\n The **${CIRCLE_JOB}** has failed!"
                success_message: ":tada: Triggered by: **${CIRCLE_USERNAME}** \\n\\n The **${CIRCLE_JOB}** has succeeded! API deployed successfully!"
